apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pws-pvc
spec:
  accessModes:
   - ReadWriteMany
  resources:
    requests:
       storage: 100Gi
  storageClassName: portworx-shared-sc
---
apiVersion: v1
kind: Pod
metadata:
  name: postgresql-pws
  labels:
    app: postgresql-pws
spec:
  volumes:
    - name: postgresql-pws-pvc
      persistentVolumeClaim:
        claimName: pws-pvc
  containers:
    - name: postgresql
      image: postgres
      env:
      - name: POSTGRES_PASSWORD
        value: "test"
      - name: POSTGRES_USER
        value: "test"
      - name: PGDATA
        value: "/var/lib/postgresql/data/data"
      volumeMounts:
       - name: postgresql-pws-pvc
         mountPath: /var/lib/postgresql/data
      ports:
       - name: postgres
         containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-pws
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: postgres
  type: NodePort
  selector:
    app: postgresql-pws
