apiVersion: v1
kind: Pod
metadata:
  name: postgresql-cephfs
  labels:
    app: postgresql-cephfs
spec:
  volumes:
    - name: postgresql-cephfs
      cephfs:
        monitors:
        - IP1:6789
        - IP2:6789
        - IP3:6789
        user: admin
        secretRef:
          name: cephfs-admin-secret
  containers:
    - name: postgresql
      image: postgres
      env:
      - name: POSTGRES_PASSWORD
        value: "test"
      - name: POSTGRES_USER
        value: "test"
      - name: PGDATA
        value: "/var/lib/postgresql/data/data"
      volumeMounts:
       - name: postgresql-cephfs
         mountPath: /var/lib/postgresql/data
      ports:
       - name: postgres
         containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-cephfs
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: postgres
  type: NodePort
  selector:
    app: postgresql-cephfs
