apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rbd-pvc
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
       storage: 100Gi
  storageClassName: rbd
---
apiVersion: v1
kind: Pod
metadata:
  name: postgresql-rbd
  labels:
    app: postgresql-rbd
spec:
  volumes:
    - name: postgresql-rbd-pvc
      persistentVolumeClaim:
        claimName: rbd-pvc
  containers:
    - name: postgresql
      image: postgres
      env:
      - name: POSTGRES_PASSWORD
        value: "test"
      - name: POSTGRES_USER
        value: "test"
      - name: PGDATA
        value: "/var/lib/postgresql/data/data"
      volumeMounts:
       - name: postgresql-rbd-pvc
         mountPath: /var/lib/postgresql/data
      ports:
       - name: postgres
         containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-rbd
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: postgres
  type: NodePort
  selector:
    app: postgresql-rbd
